version: "3.7"
services:
  web:
    container_name: web
    build: 
      context: ./web
      args:
        DOCUMENT_ROOT: /var/www/html
    ports:
      - 80:80
      - 443:443
    privileged: true
    volumes:
      - ./web/project:/var/www/html
      - ./web/conf/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80